import PushNotification from '../components/PushNotification';

// SOCKET
var socket = require('socket.io-client')('http://10.0.3.2:5000/', {
  transports: ['websocket'] // you need to explicitly tell it to use websockets
});

socket.on('connect', function(){
  console.log('Da ket noi socket!')
  // socket.emit("test","day la chuoi test");
});
socket.on('BOOKING_TOUR_CHANGE',function(data){
  console.log(data);
  PushNotification.localNotification({
    /* Android Only Properties */
    id: Math.random () * 10000, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000

    title: data.title, // (optional)
    message: data.content, // (required)
  });
})
// END SOCKET

export default socket;
