import PushNotification from '../components/PushNotification';
import { me } from '../services/api';
import { HOST } from '../constants/index';

// SOCKET
var socket = require('socket.io-client')(HOST, {
  transports: ['websocket'] // you need to explicitly tell it to use websockets
});
var profile;

socket.on('connect', function(){
  console.log('Da ket noi socket!')
  // socket.emit("test","day la chuoi test");


  me().then((response) => response.json())
      .then((responseJson) => {
        profile = responseJson.profile;
      })
      .catch((error) => console.error(error));
});

socket.on('BOOKING_TOUR_CHANGE',function(data){
  // console.log(data);

  me().then((response) => response.json())
      .then((responseJson) => {
        profile = responseJson.profile;
        if (data.idUser == profile.id){
          pushNot(data);
        }
      })
      .catch((error) => console.error(error));
})
// END SOCKET

function pushNot(data){
  PushNotification.checkPermissions(permission => {
    if (permission.alert){
      PushNotification.localNotification({
        /* Android Only Properties */
        id: Math.random () * 10000, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000

        title: data.title, // (optional)
        message: data.content, // (required)
      });
    }
  })
}

export default socket;
