export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const CHANGE_CURRENT_REGION = 'CHANGE_CURRENT_REGION';
export const GET_NEAR_LOCATION = 'GET_NEAR_LOCATION';
export const HANDLE_MODAL_LOCATION = 'HANDLE_MODAL_LOCATION';
export const CHANGE_SELECTED_LOCATION = 'CHANGE_SELECTED_LOCATION';
export const HANDLE_TOUR_CAROUSEL = 'HANDLE_TOUR_CAROUSEL';
export const CHANGE_CURRENT_ROUTE = 'CHANGE_CURRENT_ROUTE';
export const HANDLE_CURRENT_ROUTE = 'HANDLE_CURRENT_ROUTE';
export const HANDLE_CURRENT_ROUTE_ZOOM = 'HANDLE_CURRENT_ROUTE_ZOOM';
export const HANDLE_ACCESS = 'HANDLE_ACCESS';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const CHANGE_GENDER = 'CHANGE_GENDER';
export const CHANGE_BIRTHDAY = 'CHANGE_BIRTHDAY';
export const FILTER_TYPE = 'FILTER_TYPE';

export const TOUR_DETAIL_CHANGE_ID = 'TOUR_DETAIL_CHANGE_ID';
export const TOUR_DETAIL_CHANGE_ROUTES = 'TOUR_DETAIL_CHANGE_ROUTES';
export const TOUR_DETAIL_CHANGE_LOCATION = 'TOUR_DETAIL_CHANGE_LOCATION';
export const TOUR_DETAIL_SHOW_LOCATION = 'TOUR_DETAIL_SHOW_LOCATION';
export const TOUR_DETAIL_SHOW_MARKER = 'TOUR_DETAIL_SHOW_MARKER';
export const TOUR_DETAIL_CURRENT_ROUTE = 'TOUR_DETAIL_CURRENT_ROUTE';

export const BOOKING_CHANGE_INFO = 'BOOKING_CHANGE_INFO';
export const BOOKING_CHANGE_TOURTURN = 'BOOKING_CHANGE_TOURTURN';
export const BOOKING_CHANGE_NUMBER = 'BOOKING_CHANGE_NUMBER';
export const BOOKING_IS_BOOKING = 'BOOKING_IS_BOOKING';

export const SCREEN_SET_PREVIOUS = 'SCREEN_SET_PREVIOUS';

export const BOOKED_TOUR_GET_INFO = 'BOOKED_TOUR_GET_INFO';
export const BOOKED_TOUR_GET_PASSENGERS = 'BOOKED_TOUR_GET_PASSENGERS';
export const BOOKED_TOUR_GET_TOUR_INFO = 'BOOKED_TOUR_GET_TOUR_INFO';

export const SEARCH_FILTER_CHANGE = 'SEARCH_FILTER_CHANGE';

export const CURRENT_TOUR_TURN_CHANGE = 'CURRENT_TOUR_TURN_CHANGE';

export const SEARCH_NAME_CHANGE = 'SEARCH_NAME_CHANGE';

export const RECOMMEND_TOUR_ADD_LOCATION = 'RECOMMEND_TOUR_ADD_LOCATION';
export const RECOMMEND_TOUR_NEW_LOCATIONS = 'RECOMMEND_TOUR_NEW_LOCATIONS';
