export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const CHANGE_CURRENT_REGION = 'CHANGE_CURRENT_REGION';
export const GET_NEAR_LOCATION = 'GET_NEAR_LOCATION';
export const HANDLE_MODAL_LOCATION = 'HANDLE_MODAL_LOCATION';
export const CHANGE_SELECTED_LOCATION = 'CHANGE_SELECTED_LOCATION';
export const HANDLE_TOUR_CAROUSEL = 'HANDLE_TOUR_CAROUSEL';
