export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const CHANGE_CURRENT_REGION = 'CHANGE_CURRENT_REGION';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
