
const en_us = {

  name: "Name",
  message: "Message",
  setting: "Setting",
  email: "Email",
  gender: "Gender",
  birthdate: "Birthdate",
  address: "Address",
  account: "Account",
  phone: "Phone number",
  direction: "Direction",
  detail: "Detail",
  description: "Description",
  review: "Review",
  adult: "Adult",
  children: "Children",
  identity: "Identity",
  fullname: "Fullname",
  code: "Code",
  status: "Status",
  order: "Order",
  or: "Or",
  forget: "Forget",
  additionalInfo: "Additional Information",
  logout: "Logout",
  cancel: "Cancel",
  ok: "OK",
  view: "Views",
  opening: "Opening",
  closing: "Closing",
  startDate: "Start date",
  endDate: "End date",
  lasting: "Lasting",
  adultPrice: "Adult price",
  childrenPrice: "Children price",
  totalPrice: "Total price",
  adultPrice: "Adult price",
  childrenPrice: "Children price",
  date: "Date",
  price: "Price",
  booking: "Booking",
  male: "Male",
  female: "Female",
  other: "Other",
  sortBy: "Sort by",
  sortType: "Sort type",
  asc: "Ascending",
  desc: "Descending",
  otherDay: "Other day",
  daysLeft: "Days left",
  slotsLeft: "Slots left",
  lastIn: "Last in",
  days: "Days",
  detailPrice: "Detail price",
  language: "Language",
  historyBook: "History",
  changePassword: "Change Password",
  aboutUs: "About Us",
  contactScreen: "Contact",
  termsCondition: "Terms Condition",
  faqScreen: "FAQ",
  writeComment: "Write comment",
  send: "Send",
  rating: "Rating",
  comment: "Comment",
  news: "News",
  newsWithTag: "News with tags: ",
  congratulation: "Congratulation",
  search: "Search",
  checkAll: "Check all",
  uncheckAll: "Uncheck all",
  showMore: "Show more",
  bookTour: "Book Tour",
  login: "Login",
  register: "Register",
  emailOrPhone: "Email or phone number",
  password: "Password",
  lostPassword: "Lost your password",
  loginFB: "Login with Facebook",
  shareFB: "Share on Facebook",
  notHaveAccount: "You don't have an account", // You don't have an account?
  more: "More",
  tags: "Tags",
  category: "Category",
  policy: "Policy",
  schedule: "Schedule",
  day: "Day",
  choseLocations: "Chose locations",
  getRecommendedTour: "Get recommended tour",
  recommendedTour: "Recommended tour",
  noTourFound: "No tour is found",
  not_rated: "Not yet rated",
  passport: "Identity number",
  bookForYou: "Book tour for you",
  connectInternet: "Please connect to the internet",
  error: "Error",
  next: "Next",
  ageType: "Age",
  booking_term: "Booking term",
  
  // Address modal
  addressModalLabel: "Enter address",
  addressModalDescription: "Please enter your address",

  // Identity modal
  identityModalLabel: "Enter identity number",
  identityModalDescription: "Please enter your identity number",

  // Fullname modal
  fullnameModalLabel: "Enter fullname",
  fullnameModalDescription: "Please enter your fullname",

  // Change password
  newPassword: "New password",
  oldPassword: "Old password",
  confirmPassword: "Confirm new password",

  // Gender modal
  genderMocalLabel: "Choose gender",

  // Register
  registerSuccess: "You registered an account successfully! Please check your email to verify the account!", // You registered an account successfully! Please check your email to verify the account!
  haveAccount: "You have an account",

  // Forget password
  forgetPasswordSuccess: "New password has been sent to your email!", // New password has been sent to your email!
  sendRequest: "Send request",

  // Tour Detail
  tourDetail: "Tour Detail",

  // Passenger Information
  passengerInfo: "Passenger Information",
  numberOfPassengers: "Number Of Passenger",
  contactInfo: "Contact Information",

  // Payment Information
  paymentInfo: "Payment Information",

  // Confirm booking
  confirmBooking: "Confirm your booking",
  successBooking: "Successfully booking tour",

  // Tour screen
  allTourLoaded: "All tours have been loaded", //All tours have been loaded

  // Tour search
  selectDestination: "Select destination",
  selectDate: "Select date",
  maxPrice: "Max price",
  searchReset: "Reset",
  minRating: "Min Rating",

  // Search Location
  searchLocation: "Search Location",

  // Filter Location
  filterLocationType: "Filter Location Type",

  // Contact
  sendNow: "Send now",
  sendModalLabel: "You message has been sent to our email!", // You message has been sent to our email!

  // Change avatar
  changeAvatar: "Change Avatar",
  choosePhoto: "Choose Photo",

  // Change language
  changeLanguage: "Change language",

  // Detail booked tour
  detailBookedTour: "Detail Booked Tour Information", // Detail Booked Tour Information
  checkoutInfo: "Checkout Information",
  cancelTour: "Cancel tour",
  tourInfo: "Tour Information",

  // History card
  bookingDay: "Booking day",
  totalSlot: "Total slot",
  cancelTour: "Cancel tour",
  yourReason: "Your Reason",
  agreeCondition: "I have read and accepted with these above terms of condition",
  agreeAlert: "Please agree all the terms of condition",
  cancelBookingRequestSend: "Your cancel booking tour request has been send",
  noBookedTour: "You have not booked any tour",

  // Top tours
  topPopular: "Top popular tours",
  topRating: "Top rating tours",
  topView: "Top concerned tours",
  domesticTours: "Domestic Tours",
  internationalTours: "International Tours",
  domestic: "Domestic",
  international: "International",

  // Review
  reviewSuccess: "Your review has been sent",

  // Schedule
  newLocation: "You have arrived to new location",

  // Booking payment
  checkout_payment: {
    title: "PAYMENT METHOD",
    sub_title: "Please choose one of below payment method:",
    incash: "Pay in cash at Travel Tour Officeincash",
    sub_incash: "Please come to Travel Tour Office for payment and receive ticket.",
    office: "TRAVELTOUR OFFICE",
    address: "Address",
    phone: "Phone number",
    transfer: "Pay by transfer money through bankingtransfer",
    sub_transfer: "After 2h since you transfer money successfully, our staff will contact you by email or telephone",
    online: "Pay by Paypal",
    sub_online: "After your successfully payment, we will send eTicket to your email",
    pay_success: "Your payment is successfully, please click \"BOOK TOUR\" below to finish booking tour",
    pay_fail: "Your payment is not succefully, please conduct your payment through paypal to finish booking tour",
    account: "TRAVELTOUR'S BANKING ACCOUNT",
    note: "Note",
    note_content: "Please contact our staffs to confirm your booking after transferring so that our staffs check for your booking immediately and send you eTicket",
    formula: "When you transfer money, the message should be:",
    formula_content: "\"MT Booked Tour Code, Fullname\"",
    ex: "For example: \"MT 00001, TaNguyenHung\"",
    bank: "Banking account of Travel Tour Company at Vietcombank Hồ Chí Minh City - VCB",
    account_number: "Account Number",
    account_name: "Account Name",
    thank: "Thank you very much!",
    back: "BACK",
    book: "BOOK",
    choose_method: "Please choose a payment method!",
    error: "There is an error, please try book tour again!",
    full_slot: "This tour is full slot, please book another tour!",
    note_pay_1: "Please pay before",
    note_pay_2: "If the tour is not paid, the company will cancel your tour."
  },

  cancel_tour: {
    title: "CANCEL TOUR",
    tour_info: "Tour information",
    start_date: "Start date",
    book_at: "Book at",
    num_people: "Number of people",
    total_money: "Total money",
    refund_money: "Refund after cancelling tour",
    reason: "Your reason",
    terms: "Terms of condition",
    have_read: "I have read and accepted with these above terms of condition",
    send: "CANCEL TOUR",
    domestic: "CONDITIONS FOR CANCELLING TOUR",
    domestic_week_day: "For weekdays:",
    domestic_week_day_1: "If you cancel your tour within 15-19 days before the date of departure: Cost of tour cancellation: 15% of tour price.",
    domestic_week_day_2: "If you cancel your tour within 12-14 days before the date of departure: Cost of tour cancellation: 30% of tour price.",
    domestic_week_day_3: "If you cancel your tour within 08-11 days before the date of departure: Cost of tour cancellation: 50% of tour price.",
    domestic_week_day_4: "If tour cancellation within 05-07 days before the date of departure: Cost of tour cancellation: 70% of tour price.",
    domestic_week_day_5: "If canceling the tour within 02-04 days before the date of departure: Cost of tour cancellation: 90% on tour ticket price.",
    domestic_week_day_6: "If canceling the tour within 1 day before the date of departure: Cost of tour cancellation: 100% of tour ticket price.",
    domestic_holiday: "For holidays and Tet:",
    domestic_holiday_1: "If canceled within 25-29 days before the date of departure: Cost of tour cancellation: 15% of tour price.",
    domestic_holiday_2: "If canceled within 20-24 days before the date of departure: Cost of tour cancellation: 30% of tour price.",
    domestic_holiday_3: "If canceled within 17-19 days before the date of departure: Cost of tour cancellation: 50% of tour price.",
    domestic_holiday_4: "If tour cancellation within 08-16 days before the date of departure: Cost of tour cancellation: 70% of tour price.",
    domestic_holiday_5: "If canceling the tour within 02-07 days before the date of departure: Cost of tour cancellation: 90% of tour ticket price.",
    domestic_holiday_6: "If canceling the tour within 1 day before the date of departure: Cost of tour cancellation: 100% of tour ticket price.",
    note: "Note when transferring / canceling tour",
    note_content: "Tour cancellation time is calculated for working days, excluding Saturdays, Sundays & Public Holidays.",
    foreign: "CONDITIONS FOR CANCELLATION IN THE FOREIGN TOUR",
    foreign_week_day: "For weekdays:",
    foreign_week_day_1: "If canceled or transferred to other travel routes 30 days before the date of departure: No cost will be charged.",
    foreign_week_day_2: "If canceling or transferring to other tours from 24-29 days before departure: Penalty 50% of tour deposit.",
    foreign_week_day_3: "If canceling or transferring to other tours from 20-24 days before departure: Penalty 100% of tour deposit.",
    foreign_week_day_4: "If canceling the tour immediately after the Embassy or Consulate has issued a visa (for countries that need a visa): Fine 100% deposit of the tour.",
    foreign_week_day_5: "If canceling tour within 14-19 days before departure: 50% of tour price",
    foreign_week_day_6: "If canceling tour within 10-13 days before departure: Penalty 70% on tour price.",
    foreign_week_day_7: "If canceling tour within 02-09 days before departure: 90% penalty on travel ticket price.",
    foreign_week_day_8: "If canceling tour within 1 day before departure date, 100% penalty on travel ticket price.",
    foreign_holiday: "For holidays and Tet:",
    foreign_holiday_1: "Cancellation of tour immediately after the Embassy, Consulate has issued a visa: Tour cancellation cost is 100% of tour deposit.",
    foreign_holiday_2: "Tour cancellation from 30-45 days before departure: Tour cancellation cost is 30% of total tour price.",
    foreign_holiday_3: "Cancellation of tour from 16 - 29 days before departure date: Tour cancellation cost is 60% of total tour price.",
    foreign_holiday_4: "Tour cancellation from 08 - 15 days before departure: Tour cancellation cost is 90% of total tour price.",
    foreign_holiday_5: "Cancellation of tour from 01 - 07 days before departure date: Tour cancellation fee is 100% of total tour price.",
    foreign_holiday_6: "Tours on holidays and New Year are tours that take place in one of the holidays and Tet holidays.",
    success: "Your request is sent to us succefully!",
    reply: "We will make a phone call and send email to you after processing your request!",
    thank: "Thank you!",
    reason_required: "Reason is required!",
    not_agree: "You haven't agreed with our terms of condition yet!",
    error: "There is an error, please try again!",
    close: "CLOSE",
    busy: "Busy work unexpectedly",
    sick: "Sick, hospitalized and cannot go",
    other: "Other"
  },

  about: {
    title: "ABOUT US",
    part_1: "First, ",
    sub_part_1: "our company would like to send our cordial greetings to customers and partners. We wish our customers and partners abundant health and success.",
    part_2: "Scope of activities: ",
    sub_part_2: "Business travel domestic and international.",
    part_3: "Our company ",
    sub_part_3: "was established on March 25, 2017 with the initial business activity of organizing tourism programs for foreign tourists to visit Vietnam, so far has spent 2 years of construction and development (2017–2019). , our company has been constantly growing, the business sector has been increasingly expanded: domestic and foreign tourism business. The company has also built a branch system in Hanoi, Da Nang and Ho Chi Minh City. Ho Chi Minh and Can Tho and the dealer network in many provinces and cities of the country. As a company established 26 years ago, the reputation is extremely high in the field of tourism and travel. Our company provides not only useful information for people with travel needs but also a place to provide professional travel services, highly appreciated by customers. After years of competition, striving and proving, we have been honored in the top most famous travel companies in Vietnam. With the criteria of high quality, safe, unmodified tour, the best price in the market ensures visitors have the most interesting experiences, the most professional service when buying tours here. We serve tourists traveling on all 5 continents, traveling abroad here are highly trusted and appreciated by customers. Tour service is quick and easy, quick operation is a leading company in terms of quality and professional service style.",
    part_4: "Professional staff.",
    sub_part_4: "The company is proud to create a good corporate culture with a friendly working environment, the members work together, help and support each other when needed, a professional working environment from office staff to the direction tour guide, always give advice and accurate travel information to customers. A well-trained, professional and friendly tour guide team who understands foreign culture, can introduce Vietnamese visitors useful information, also aims to create a good feeling among Vietnamese people. and international friends.",
    part_5: "Vision and mission.",
    sub_part_5: "The company strives to keep its position as one of the leading travel companies in Vietnam and the region in terms of scale, quality and prestige. With abundant resources, strong financial resources, experience and reputation in the field of tourism services, sustainable relationships with major partners around the world, dynamic and professional staff We always try our best to provide our customers with the most valuable travel products.",
    part_6: "Business philosophy.",
    sub_part_6: "The company always attaches great importance to the sense of responsibility of the business to the community and the environment, develops business activities on the basis of harmonizing business interests with the social community, friendly with the natural environment.",
    part_7: "Core values.",
    sub_part_7_1: "Always comply with the standards and quality commitments announced to customers.",
    sub_part_7_2: "See the quality of service and customer convenience is the first criterion in the orientation and operation of the company.",
    sub_part_7_3: "Pioneering in opening up the inspirations and hidden expectations of customers to bring to customers the unique and new tourist products that customers can only find in our company.",
    city_tour: "CITY TOURS",
    culture: "CULTURAL AND ARTS",
    honeymoon: "HONEYMOON",
    luxury: "LUXURY RESORTS",
    adventure: "ADVENTURE",
    cool: "COOL EXPERIENCES",
    do_right_1: "Doing the right thing,",
    do_right_2: "at the right time.",
    branch: "BRANCHES",
    tours: "TOURS",
    destination: "DESTINATIONS",
    staff: "STAFF",
    support: "SUPPORT",
    best: "BEST TOURS",
    resort: "RESORTS",
    guide: "GUIDES",
    support_content: "At any time anywhere, we are always ready to receive and appreciate all your questions and suggestions, we will quickly resolve and have timely feedback for all problems. Any problems or unsatisfactoriness of customers. Get Customer Satisfaction as our Happiness.",
    guide_content: "A well-trained, professional and friendly tour guide team who understands foreign culture, can introduce Vietnamese visitors with useful information, also aims to create a good feeling among Vietnamese people. and international friends.",
    resort_content: "Resort at the most luxurious and luxurious resorts in the world, the best destinations named as paradise resting place in the world.",
    best_content: "When ordering the tour products of our company, you will feel completely assured and satisfied in all aspects because the company always provides you with the things you want and care about, you will served by the company in accordance with the motto Customer is god."
  },

  contact: {
    title: "CONTACT",
    drop: "DROP US A LINE",
    drop_content: "Please contact us for advice, answer questions and achieve what you expect of a dream vacation.",
    direct: "DIRECT CONTACT",
    direct_content: "If you have a problem that needs answering please contact us directly, please see the information below:",
    website: "CONTACT THROUGH THE WEBSITE SYSTEM",
    website_1: "We always welcome all suggestions, your problems need to be answered.",
    website_2: "Please use the forum to ask questions when you have a problem that can't be solved. Our staff will answer your problems quickly.",
    website_3: "To make contact, please fill in the form below.",
    address: "Address",
    city: "City",
    phone: "Phone",
    opening: "Opening",
    closing: "Closing",
    message: "Message",
    name: "Name",
    email_format: "Email must be in right format!",
    email_required: "Email is required!",
    fullname_required: "Fullname is required!",
    fullname_format: "Fullname should not contain numbers",
    message_required: "Message is required!",
    success: "Successfully!",
    success_content_1: "Your message is sent to us.",
    success_content_2: "Please check your email in a few day.",
    ok: "OK",
    error: "There is an error, please try again!",
    send: "SEND NOW"
  },

  terms: {
    title: "TERMS OF CONDITION",
    sub_title: "These terms of use govern your use of our company website. Your use of this website means you accept these Terms.",
    part_1: "Company rights",
    sub_part_1_1: "The company will proceed to provide the best services to customers after completing the procedures and conditions stated by the company.",
    sub_part_1_2: "In case the customer provides incorrect information to the company, or violates the law, we reserve the right to refuse or terminate the service.",
    sub_part_1_3: "Our company reserves the right to use the services and content on the company's website according to copyright laws and regulations on the protection of intellectual property in Vietnam. All acts of illegally copying, using and disseminating such rights are strictly prohibited.",
    sub_part_1_4: "Our company reserves the right to change the price schedule of the tour and the payment method according to the needs and conditions of the tour.",
    part_2: "Obligations of the company",
    sub_part_2_1: "The company will conduct deployment and cooperation with travel partners in building a system of services, utility tools for passengers.",
    sub_part_2_2: "The company is always responsible for upgrading equipment, adding services and quality related to tourism activities, serving customers.",
    sub_part_2_3: "The company will endeavor to the highest extent possible and conditions to maintain normal travel activities. However, if the above incidents occur outside the ability to control, force majeure cases cause damage to customers, our company does not have to bear joint responsibility.",
    sub_part_2_4: "Security: Commitment to keep all your information confidential when registering to use the tour booking service on the website.",
    part_3: "Conditions for participating in customer tours.",
    sub_part_3_1: "1. Register for a tour program.",
    sub_part_3_1_1: "The company will provide customers with all free travel information.",
    sub_part_3_1_2: "Customers can register for the tour directly at the company's office or online on the website. Tour registration must be made at least 3 days in advance and customers will confirm the specific tour program through the contract.",
    sub_part_3_1_3: "Special requests from customers must be notified immediately at the time of registration. The company will try to meet these needs in its capacity.",
    sub_part_3_2: "2. Price of travel program.",
    sub_part_3_2_1: "The price of the tour program is guaranteed during the term of the contract.",
    sub_part_3_2_2: "Price includes details in each specific program.",
    sub_part_3_2_3: "The price of tourism programs can increase during the Christmas, New Year, Vietnamese Lunar New Year, April 30 and National Day September 2, the Company is responsible for specifically announcing the price according to each program for customers.",
    sub_part_3_2_4: "Rate applies for children (No extra bed is generated):",
    sub_part_3_2_4_1: "Over 11 years old: Apply adult price.",
    sub_part_3_2_4_2: "From 05 to under 11 years old: 75% of adult prices; under 05 years old: free travel service (Costs incurred at the point of Dad, mother directly pay - Particularly for children under 2 years old airfare 10% of air fare)",
    sub_part_3_3: "3. Defer to cancel the program.",
    sub_part_3_3_1: "In case the trip is canceled by the Company: The company must immediately notify the customer and repay the customer all the money the customer has reserved or arranged to negotiate with other travel program customers other partners serve.",
    sub_part_3_3_2: "In case the trip is canceled by the customer: Before the departure date, if the customer cannot attend the trip for any reason, he must immediately notify the Company in writing or by mail and customer. subject to the following procedures:",
    sub_part_3_3_2_1: "Cancellation 05 days in advance: Customers will pay the costs that the Company must pay for canceling the service.",
    sub_part_3_3_2_2: "Cancellation before 72 hours compared to departure time: 50% of the total value of the travel program.",
    sub_part_3_3_2_3: "Cancellation 24 hours prior to departure: 75% of the total value of the tour program.",
    sub_part_3_3_2_4: "Cancel after 24 hours compared to departure time: 100% of the total value of the tour program.",
    sub_part_3_3_2_5: "No refunds for customers who leave the tour program And depending on the specific tour, will be clearly informed in each tour.",
    sub_part_3_3_3: "Force Majeure: If the travel program is canceled or changed due to force majeure (Fire, weather, natural disaster, war ...), then both parties will not be liable to any compensation obligation Completion of losses has occurred and does not assume any liability.",
    sub_part_3_4: "4. Payment of money.",
    sub_part_3_4_1: "Payment by cash or bank transfer.",
    sub_part_3_4_2: "Customers must deposit at least 50% of the tour package price when officially registering and signing the contract. The remaining amount must be paid out before 07 days of departure.",
    city_tour: "CITY TOURS",
    culture: "CULTURAL AND ARTS",
    honeymoon: "HONEYMOON",
    luxury: "LUXURY RESORTS",
    adventure: "ADVENTURE",
    cool: "COOL EXPERIENCES"
  },

  faq: {
    title: "FAQ",
    sub_part: "Factual information.",
    sub_part_title_1: "1. What hours are told?",
    sub_part_1: "All flight hours are stated in local time. For example, if it indicates that the flight departs at 15:00 from Arlanda and arrives in London at 16:30, the flight time is 2.5 hours, because the hour in the UK is 1 hour later than Sweden. For example, if you fly from the United States, you usually leave the United States in the evening and go to Europe the next day. This information is told with a new date along with the times.",
    sub_part_title_2: "2. When I booked my trip I did not receive the travel documents by email, what should I do?",
    sub_part_2: "Your travel documents are automatically sent to the email address you provided when making a tour request. If you have not received travel documents, you may have provided an incorrect email address. Travel documents contain all the details of your reservation request. Some email servers can sometimes categorize these emails as \"spam\". Make sure the email has not been classified as spam. You can always contact us and we will send you new travel documents. Note that it is very important to provide us with the correct email address, as we will also use this address to send you any calendar change information or other changes to your love. request your tour.",
    question: "MOST FREQUENT QUESTION - CUSTOMER",
    question_1: "How are prices indicated in search results when I want to make a tour request?",
    answer_1: "Rates are always stated as the price per person. If you have both children and adults in search requests, the total for all passengers will be displayed as well as the price per adult. When you select an option and continue, the price will be indicated as adults and children. The total price is always displayed.",
    question_2: "How long can I book a tour?",
    answer_2: "You can book the tour as soon as the company has the tour until 3 days before the departure date if the tour is available.",
    question_3: "Can the price on the website change?",
    answer_3: "The price on our website is the Company has estimated in advance, the costs are calculated correctly, so the price does not change during the tour process, once you have chosen the option you want.",
    question_4: "Are there any fees when I pay by card?",
    answer_4: "Any applicable fees will be displayed at the time of making the tour request.",
    question_5: "How can I get information about any calendar changes?",
    answer_5: "Departure time can be changed in a short time. It is important that you check the email address you provided when booking the tour because any calendar changes will be sent there. You must use an email address that you can also check while away, because calendar changes can sometimes appear after you have started. You can always check the departure time using the link we give you in your travel documents.",
    question_6: "I will go with an infant. Do I need any special information?",
    answer_6: "If you have bought a tour and you travel long distance, we may request a cradle for your baby. To do this, we need the following information: the child's date of birth and the height and weight of the estimate on the day of departure. In some cases we may also order infant food and special seats for passengers with newborn babies. However, we can never guarantee these seats, because airlines sometimes make changes (changing aircraft types, changing schedules, etc.) can lead to inability to respond. Your request.",
    question_7: "Do children have their own passports?",
    answer_7: "Yes, all children must have their own passports. Cannot list only children in parents' passports.",
    question_8: "Why can't I access the tour booking information in my account. How can I log in?",
    answer_8: "To book a trip when you book a tour on our website you must log in to your account when you make a tour request.",
    question_9: "The password to my account has no effect. How can I change my password?",
    answer_9: "Click on the \"Login\" button on our home page where you will find a link, you can open this link to get a new password. Click on the \"Forgot password\" link and enter your email address and we will send you instructions on how to install a new password.",
    question_10: "I have problems activating my account. Does it matter?",
    answer_10: "There may be security settings in your email that prevent you from receiving verification emails. First check your security settings. If this doesn't work, contact us again so we can reactivate your account.",
    get_in_touch: "Get In Touch",
    name: "Name",
    message: "Message",
    send: "SEND NOW",
    package: "PACKAGES",
    best: "Best Promotions",
    email_format: "Email must be in right format!",
    email_required: "Email is required!",
    fullname_required: "Fullname is required!",
    fullname_format: "Fullname should not contain numbers",
    message_required: "Message is required!",
    success: "Successfully!",
    success_content_1: "Your message is sent to us.",
    success_content_2: "Please check your email in a few day.",
    ok: "OK",
    error: "There is an error, please try again!"
  },

  my_booking: {
    title: "MY BOOKING",
    code: "Booking code",
    book_day: "Booking day",
    total_slot: "Total slot",
    total_money: "Total money",
    status: "Status",
    detail: "Detail",
    cancel: "Cancel",
    pending: "Pending",
    solved: "Solved",
    booked: "Not paid yet",
    paid: "Paid",
    cancelled: "Cancelled",
    bookDayDesc: "Booking Day Descending",
    bookDayAsc: "Booking Day Ascending",
    priceDesc: "Price Descending",
    priceAsc: "Price Ascending",
    no_tour: "You have no tour in your Booking History now.",
    search_tour: "Tour's name"
  },

  detail_booked_tour: {
    title: "DETAIL BOOKED TOUR INFORMATION",
    status: "Status",
    booked: "Not Paid Yet",
    paid: "Paid",
    cancelled: "Cancelled",
    pending_cancel: "Pending Cancel",
    finished: "Finished Tour",
    confirm_cancel: "Confirm Cancel",
    refunded: "Refunded",
    not_refunded: "Not Refunded",
    tour_info: "Tour information",
    checkout_info: "Checkout information",
    contact_info: "Contact information",
    passenger_info: "Passenger information",
    code: "Tour Code",
    start_date: "Start date",
    end_date: "End date",
    lasting: "Lasting",
    adult_price: "Adult price",
    children_price: "Children price",
    total_price: "Total price",
    num_adult: "Number of adults",
    num_children: "Number of children",
    fullname: "Fullname",
    phone: "Phone number",
    address: "Address",
    gender: "Gender",
    birthdate: "Birthdate",
    age: "Age",
    passport: "Identity number",
    male: "Male",
    female: "Female",
    other: "Other",
    Adult: "Adult",
    Children: "Children",
    days: "days",
    tracking: "TRACKING THIS TOUR",
    just_come: "YOU JUST COME TO",
    just_come_lower: "You just come to",
    reach_location: "Reach location",
    online: "Online",
    incash: "In cash",
    transfer: "Banking transfer",
    method: "Payment method:",
    confirm_cancel_content: "Confirm cancel tour in:",
    refund_money: "Refund money:",
    refund_note: "After three working day (except Saturday and Sunday) since confirm cancel time, you can come to TRAVEL TOUR Office to receive refunds",
    refund_period: "Deadline to receive refunds:",
    refund_time: "Received refunds in:",
    people_pay: "People paying:",
    people_pay_help: "People help pay:",
    people_cancel: "People cancel tour directly:",
    people_refund: "People receive refunds:",
    people_refund_help: "People help receive refunds:"
  },

  map_filter: {
    Airport: "Airport",
    Amusement: "Amusement",
    Bank: "Bank",
    Bus_Stop: "Bus stop",
    Cafe_Milk_Tea: "Cafe & Milk tea",
    Church: "Church",
    Gas_Station: "Gas Station",
    Hospital: "Hospital",
    Hotel: "Hotel",
    Mall: "Mall",
    Market: "Market",
    Night_Market: "Night Market",
    Museum: "Museum",
    Park: "Park",
    Police: "Police",
    Restaurant: "Restaurant",
    Sport: "Sport",
    Travel_Agency: "Travel Agency",
    Temple: "Temple",
    Tourist_Area: "Tourist Area",
    Start_End: "Start End",
  },

  ERR_USERNAME: 'Email or Phone number must be in right format',
  ERR_PASSWORD: 'Password is required',
  ERR_FULLNAME: 'Fullname is required',
  ERR_NAME: 'Name is required',
  ERR_PHONE: 'Phone number is required',
  ERR_EMAIL: 'Email is required',
  ERR_EMAIL_VALIDATE: 'Wrong email type',
  ERR_CONFIRM_PASSWORD: 'Password and Confirm password must be match!',
  ERR_PHONE_LENGTH: 'Phone number must be 10 digits!',
  ERR_ALL_FIELD: 'All fields is required',
  ERR_MESSAGE: 'Message is required',

  ERR_BOOKING_CONTACT_INFO: 'All contact information is required',
  ERR_BOOKING_PASSENGER_INFO: 'Fullname, Birthdate, Gender of passenger are required',
  ERR_BOOKING_PASSENGER_MIN: 'There must be 1 passenger',

  ERR_RATING: "Rating is required",
  ERR_COMMENT: "Comment is required",

  SUCCESS_CHANGE_PASSWORD: "Change Password Successfully",
}

export default en_us;
